const opcao = sessionStorage.getItem('opcaoEscolhida')

if(opcao == "1"){
    document.querySelector("#titulo").innerHTML = "<span>|</span> Refúgio Azul"
    document.querySelector("#localizacao").innerHTML = "Rua não sei"
    document.querySelector("#img-principal").src = "../img/ongs/ondas-do-mar 1.png"
    document.querySelector("#pr1").innerHTML = "fazer faxina"
    document.querySelector("#hr1").innerHTML = "14hrs as 12hrs"
    document.querySelector("#pr2").innerHTML = " "
    document.querySelector("#hr2").innerHTML = " "
    document.querySelector("#pr3").innerHTML = " "
    document.querySelector("#hr3").innerHTML = ""
    document.querySelector("#pr4").innerHTML = ""
    document.querySelector("#hr4").innerHTML = ""
    document.querySelector("#descricao").innerHTML = "dsfssssgfgbfgf"
    document.querySelector("#parc1").src = "../img/ongs/ondas-do-mar 1.png"
    document.querySelector("#parc2").src = "../img/ongs/ondas-do-mar 1.png"
    document.querySelector("#parc3").src = "../img/atividade"
    document.querySelector("#logo-ong").src = "../img/atividade"
    document.querySelector("#nome-ong").innerHTML = ""
    document.querySelector("#descricao-ong").innerHTML = ""
}else if(opcao == "3"){
    document.querySelector("#titulo").innerHTML = "Horizonte Verde"
    document.querySelector("#localizacao").innerHTML = "Rua não sei"
    document.querySelector("#img-principal").src = "../img/ongs/ondas-do-mar 1.png"
    document.querySelector("#pr1").innerHTML = "fazer faxina"
    document.querySelector("#hr1").innerHTML = "14hrs as 12hrs"
    document.querySelector("#pr2").innerHTML = " "
    document.querySelector("#hr2").innerHTML = " "
    document.querySelector("#pr3").innerHTML = " "
    document.querySelector("#hr3").innerHTML = ""
    document.querySelector("#pr4").innerHTML = ""
    document.querySelector("#hr4").innerHTML = ""
    document.querySelector("#descricao").innerHTML = "dsfssssgfgbfgf"
    document.querySelector("#parc1").src = "../img/ongs/ondas-do-mar 1.png"
    document.querySelector("#parc2").src = "../img/ongs/ondas-do-mar 1.png"
    document.querySelector("#parc3").src = "../img/atividade"
    document.querySelector("#logo-ong").src = "../img/atividade"
    document.querySelector("#nome-ong").innerHTML = ""
    document.querySelector("#descricao-ong").innerHTML = ""
    
}